import { Song, SongConfig, Pattern, PatternLabel, SectionRole } from './types';

// Strip trailing zeros from number arrays for compact output
function fmtParams(arr: number[]): string {
  let last = arr.length - 1;
  while (last > 0 && (arr[last] === 0 || arr[last] === undefined)) last--;
  return '[' + arr.slice(0, last + 1).map(v => v == null ? '' : v).join(',') + ']';
}

function fmtParamsCompact(arr: number[]): string {
  let last = arr.length - 1;
  while (last > 0 && (arr[last] === 0 || arr[last] === undefined)) last--;
  return '[' + arr.slice(0, last + 1).map(v => v == null ? '' : +v.toFixed(4)).join(',') + ']';
}

function fmtChannel(ch: number[]): string {
  let last = ch.length - 1;
  while (last > 1 && ch[last] === 0) last--;
  return '[' + ch.slice(0, last + 1).join(',') + ']';
}

function songToZzfxmArrays(song: Song) {
  const patternArrays: number[][][] = [];
  for (const label of song.patternOrder) {
    patternArrays.push(song.patterns[label]);
  }
  return {
    instruments: song.instruments,
    patterns: patternArrays,
    sequence: song.sequence,
    bpm: song.config.bpm,
  };
}

// Full Song → JSON for lossless round-trip
function songToJson(song: Song): string {
  const { instruments, patterns, sequence, bpm } = songToZzfxmArrays(song);
  return JSON.stringify({
    v: 1,
    config: song.config,
    patternOrder: song.patternOrder,
    patternRoles: Object.fromEntries(
      song.patternOrder.map(l => [l, song.patternRoles[l]])
    ),
    instruments,
    patterns,
    sequence,
  });
}

// Export a usable JS file — ready to drop into a game project
// The @zzfx-studio line embeds full song JSON for lossless re-import
export function songToCode(song: Song): string {
  const { instruments, patterns, sequence, bpm } = songToZzfxmArrays(song);

  const lines: string[] = [];

  // Machine-readable JSON for re-import (single line, stays out of the way)
  lines.push('// Generated by ZZFx Gen Studio');
  lines.push(`// @zzfx-studio ${songToJson(song)}`);
  lines.push('');

  // Human-readable, usable JS
  lines.push('let instruments = [');
  for (const inst of instruments) {
    lines.push('  ' + fmtParams(inst) + ',');
  }
  lines.push('];');
  lines.push('');

  lines.push('let patterns = [');
  for (let pi = 0; pi < patterns.length; pi++) {
    const label = song.patternOrder[pi];
    const role = song.patternRoles[label];
    lines.push(`  [ // ${label} (${role})`);
    for (const ch of patterns[pi]) {
      lines.push('    ' + fmtChannel(ch) + ',');
    }
    lines.push('  ],');
  }
  lines.push('];');
  lines.push('');

  lines.push(`let sequence = [${sequence.join(',')}];`);
  lines.push(`let BPM = ${bpm};`);
  lines.push('');
  lines.push('// Usage: zzfxP(...zzfxM(instruments, patterns, sequence, BPM));');

  return lines.join('\n');
}

// Compact one-liner for clipboard
export function songToClipboard(song: Song): string {
  const { instruments, patterns, sequence, bpm } = songToZzfxmArrays(song);

  const instStr = '[' + instruments.map(i => fmtParamsCompact(i)).join(',') + ']';
  const patStr = '[' + patterns.map(pat =>
    '[' + pat.map(ch => fmtChannel(ch)).join(',') + ']'
  ).join(',') + ']';
  const seqStr = '[' + sequence.join(',') + ']';

  return `zzfxM(${instStr},${patStr},${seqStr},${bpm})`;
}

// Import: parse the @zzfx-studio JSON line
export function codeToSong(code: string): Song | null {
  try {
    const match = code.match(/\/\/ @zzfx-studio (.+)/);
    if (!match) return null;

    const data = JSON.parse(match[1]);
    if (!data.config || !data.instruments || !data.patterns || !data.sequence) return null;

    const config: SongConfig = data.config;

    // Pad instruments back to 20 params
    for (const inst of data.instruments) {
      while (inst.length < 20) inst.push(0);
    }

    const patternOrder: PatternLabel[] = data.patternOrder;
    const patternRoles = {} as Record<PatternLabel, SectionRole>;
    const patternMap = {} as Record<PatternLabel, Pattern>;

    for (let i = 0; i < patternOrder.length; i++) {
      const label = patternOrder[i];
      patternRoles[label] = data.patternRoles?.[label] ?? 'verse';

      // Pad channels back to 34 (inst + pan + 32 notes)
      const pat = data.patterns[i];
      for (const ch of pat) {
        while (ch.length < 34) ch.push(0);
      }
      patternMap[label] = pat as Pattern;
    }

    return {
      config,
      instruments: data.instruments,
      patterns: patternMap,
      patternRoles,
      sequence: data.sequence,
      patternOrder,
    };
  } catch (e) {
    console.error('Failed to parse song:', e);
    return null;
  }
}
